spring.application.name=benz-rental-api
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5433}/${PGDATABASE:benzride_db}?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=${PGUSER:benzride_user}
spring.datasource.password=${PGPASSWORD:benzride123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

xendit.api-key=${XENDIT_API_KEY:your_xendit_secret_key_here}
xendit.callback-token=${XENDIT_CALLBACK_TOKEN:your_xendit_callback_token_here}
xendit.base-url=https://api.xendit.co
xendit.success-redirect-url=${APP_URL:http://localhost:5173}/booking/success
xendit.failure-redirect-url=${APP_URL:http://localhost:5173}/booking/failed

app.server-url=${APP_SERVER_URL:http://localhost:8080}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

jwt.secret=NjhkMzQyMWE4YzQ3YjZkOGYzZTI1MWM4ZGIwYzNmNjI4YWU5YmQ0YzE2ODI5YTNk
jwt.expiration-ms=86400000

spring.jackson.mapper.accept-case-insensitive-enums=true

logging.level.benzride_api=DEBUG
logging.level.org.springframework.security=WARN
